# Generated by Django 4.2.15 on 2024-08-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dishes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dishes',
            options={},
        ),
        migrations.AlterField(
            model_name='dishes',
            name='categoryType',
            field=models.CharField(choices=[('Salads', 'Salads'), ('Main course', 'Main course'), ('Second course', 'Second course'), ('Desserts', 'Desserts')], max_length=20, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='recipe',
            field=models.TextField(verbose_name='Recipe'),
        ),
    ]
